### ISSUE TITLE
Babel-*@^6.6.0 breaks this plugin

### ISSUE THREAD

**Issue by thangngoc89** [istarkov/babel-plugin-webpack-loaders#39] opened 2016-03-01 05:04 UTC
I get up this morning and receive a tons of build alerts from greenkeeper.

https://travis-ci.org/thangngoc89/blog/jobs/112740937#L1357

No idea how to fix it

**Comment by MoOx** [comment] 2016-03-01 06:58
Running test on master with a fresh node install give the following error:

```
Error: Cannot find module 'empty'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/test/deepTree/deep.spec.js:7:14)
    at Module._compile (module.js:413:34)
    at loader (/Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/MoOx/Sync/Development/babel-plugin-webpack-loaders/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

```

It seems that this line is not doing its job https://github.com/istarkov/babel-plugin-webpack-loaders/blob/b1c1e4b56dfc901c42e19f80992c1dabbca87259/src/plugin.js#L226
(empty should be replaced with a local filename from what I understand).

**Comment by istarkov** [comment] 2016-03-01 09:31
Short problem details (If you have ideas please help):

The problem is next: 

For a file
```javascript
import css from './some.css';
```

Prev version of `babel` with next simple babel plugin

```
export default function ({types: t}) {
  return {
    visitor: {
      CallExpression(path) {
        const { callee: { name: calleeName } } = path.node;
        console.log('calleeName', calleeName);
      }
    }
  };
}
```

Provide output 

```
calleeName require
calleeName _interopRequireDefault
```

But current babel does not process imports (after transformations 2 require) as a CallExpression (and this is strange)

I will investigate further

**Comment by MoOx** [comment] 2016-03-01 09:33
I tried to read all commits but can't find anything obvious to me (I don't know how to make babel plugin yet ^^)

https://github.com/babel/babel/compare/97a443466334a9b2543da1a0a006a416a3b84370...ddc82a848c451c45c100aed1d69938cefa91fd19

**Comment by istarkov** [comment] 2016-03-01 10:09
Looks like bug in babel

Next plugin 

```javascript
export default function (/* { types: t } */) {
  return {
    visitor: {
      CallExpression(path) {
        const { callee: { type, name } } = path.node;
        console.log('calleeName', type, name);
      },
    },
  };
}
```

for a file 

```javascript
import css from './some';
```

outputs 

```
calleeName Identifier require
calleeName Identifier _interopRequireDefault
```

but for a same file + small part of code

```javascript
import css from './some';
console.log(css);
```

outputs

```
calleeName MemberExpression undefined
```

but must output 

```
calleeName MemberExpression undefined
calleeName Identifier require
calleeName Identifier _interopRequireDefault
```


Will report now

**Comment by MoOx** [comment] 2016-03-01 10:13
Thanks for your investigation !

**Comment by istarkov** [comment] 2016-03-01 10:20
Placed description here
https://phabricator.babeljs.io/T7168

**Comment by istarkov** [comment] 2016-03-01 10:31
Looks like a duplicate of this https://phabricator.babeljs.io/T7164

**Comment by MoOx** [comment] 2016-03-01 10:45
Subscribed to both issues :)

**Comment by thangngoc89** [comment] 2016-03-01 12:34
Thank you for your investigation

**Comment by istarkov** [comment] 2016-03-01 20:01
Looks like babel fixed, for now current tests works well.

**Comment by istarkov** [comment] 2016-03-01 20:33
I also installed greenkeeper ;-) looks like amazing tool
https://github.com/istarkov/babel-plugin-webpack-loaders/pull/40

**Comment by MoOx** [comment] 2016-03-01 20:38
Oh ! Will take a look, thanks !

**Comment by MoOx** [comment] 2016-03-01 21:02
Back to normal, you can close. Thanks!

**Closed** 2016-03-01 21:09 UTC
